name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Output
      run: |
        mkdir Output
    - name: Copy Code
      run: |
        cp Windows Output/Windows -r &&
        cp Utils Output/Utils -r &&
        cp Run.bat Output/
    - name: Compress Code
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r Output.zip Output
    - name: Publish Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Rocket
        path: |
          Output.zip
